services:
    db:
      image: postgres:latest
      hostname: db
      environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=context
      ports:
      - "5433:5432"
